# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TabbedBarExample' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TabbedBarExample
    pod 'Alamofire', '~> 4.5'
    pod 'YouTubePlayer'
    pod 'DropDown'

  target 'TabbedBarExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TabbedBarExampleUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
